title: Samir's blog
description: "Hello. You are welcome to my blog. Trying to find my way in software development, mathematics and life. Feed free to enjoy some of my toughts."
welcome_description: "Hello. You are welcome to my blog. Trying to find my way in software development, mathematics and life. Feed free to enjoy some of my toughts."
twitter_username: samirhali
github_username: riemass
language: en
post_limit: 10
plugins: [jekyll-paginate]
paginate_path: "/page/:num/"
permalink: none
markdown: kramdown
